In [1]:
import base64
from PIL import Image
from keras.applications.vgg16 import preprocess_input
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np 
from keras.preprocessing import image

model = load_model('./facerecognition_first_modelvgg16.h5')

face_cascade = cv2.CascadeClassifier('./haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image

    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)

    if faces is ():
        return None

    # Crop all faces found
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 255), 2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Face recognition

url = 'http://192.168.43.158:4747'
cap = cv2.VideoCapture(url+"/video")

while True:
    _, frame = cap.read()
    face = face_extractor(frame)

    if type(face) is np.ndarray:
        face = cv2.resize(face, (224,224))
        img = Image.fromarray(face, 'RGB')

        img_array = np.array(img)
        img_array = np.expand_dims(img_array, axis=0)
        prediction = model.predict(img_array)
        print(prediction)

        name = 'None matching'

        if(prediction[0][1] > 0.7):
            name = 'Mom'
        elif(prediction[0][0] > 0.7):
            name = 'Shashank'
        elif(prediction[0][2] > 0.7):
            name = 'Dad'
        cv2.putText(frame, name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
    else:
        cv2.putText(frame, "No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()


Using TensorFlow backend.


[[1.00000000e+00 1.19436915e-26 3.12248076e-08]]
[[1.0000000e+00 1.1543446e-28 1.0548553e-08]]
[[1.0000000e+00 6.9781801e-28 1.0494347e-12]]
[[1.0000000e+00 2.0634901e-24 0.0000000e+00]]
[[1.0000000e+00 2.7453861e-23 1.1127449e-24]]
[[1.0000000e+00 3.7918082e-24 1.0583015e-19]]
[[1.0000000e+00 1.3635320e-21 5.3237904e-27]]
[[1.0000000e+00 3.7591784e-36 0.0000000e+00]]
[[1.000000e+00 2.049779e-29 0.000000e+00]]
[[1.000000e+00 5.684672e-31 0.000000e+00]]
[[1.0000000e+00 3.2145968e-22 0.0000000e+00]]
[[1.000000e+00 9.462755e-31 0.000000e+00]]
[[1.0000000e+00 1.1705414e-31 2.3825776e-38]]
[[1.0000000e+00 1.0887269e-33 0.0000000e+00]]
[[1.0000000e+00 1.7033931e-32 0.0000000e+00]]
[[1.0000000e+00 1.0294456e-26 2.0307317e-24]]
[[1.0000000e+00 3.3863469e-33 5.8658325e-33]]
[[1.0000000e+00 2.1000378e-29 0.0000000e+00]]
[[1.0000000e+00 1.2102457e-36 0.0000000e+00]]
[[1.0000000e+00 3.8328986e-28 0.0000000e+00]]
[[1.0000000e+00 2.3690736e-23 0.0000000e+00]]
[[1.000000e+00 1.907299e-28 0.000000e+00

NameError: name 'video_capture' is not defined